version: "3"
services:
    postgres:
        image: postgres:10.6
        restart: always
        volumes:
            - /tmp/postgresql/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 12345678
            POSTGRES_USER: rs_master
            POSTGRES_DB: rs_school
        ports:
            - 5432:5432
