version: "3"
services:
    ui:
        image: rsschool/ui:latest
        ports:
            - 8081:8080
        environment:
            RS_HOST: ${RS_HOST}
    api:
        image: rsschool/api:latest
        ports:
            - 8080:8080
        environment:
            RSSHCOOL_API_AUTH_CALLBACK: ${RSSHCOOL_API_AUTH_CALLBACK}
            RSSHCOOL_API_AUTH_CLIENT_ID: ${RSSHCOOL_API_AUTH_CLIENT_ID}
            RSSHCOOL_API_AUTH_CLIENT_SECRET: ${RSSHCOOL_API_AUTH_CLIENT_SECRET}
            RSSHCOOL_API_AUTH_SUCCESS_REDIRECT: ${RSSHCOOL_API_AUTH_SUCCESS_REDIRECT}
            RSSHCOOL_API_SESSION_KEY: ${RSSHCOOL_API_SESSION_KEY}
            RSSHCOOL_API_PG_HOST: ${RSSHCOOL_API_PG_HOST}
            RSSHCOOL_API_PG_USERNAME: ${RSSHCOOL_API_PG_USERNAME}
            RSSHCOOL_API_PG_PASSWORD: ${RSSHCOOL_API_PG_PASSWORD}
            RSSHCOOL_API_PG_DATABASE: ${RSSHCOOL_API_PG_DATABASE}
            RSSHCOOL_API_ADMIN_USERNAME: ${RSSHCOOL_API_ADMIN_USERNAME}
            RSSHCOOL_API_ADMIN_PASSWORD: ${RSSHCOOL_API_ADMIN_PASSWORD}
            RSSHCOOL_API_INTEGRATIONS_HEROES_URL: ${RSSHCOOL_API_INTEGRATIONS_HEROES_URL}
            RSSHCOOL_API_INTEGRATIONS_HEROES_USERNAME: ${RSSHCOOL_API_INTEGRATIONS_HEROES_USERNAME}
            RSSHCOOL_API_INTEGRATIONS_HEROES_PASSWORD: ${RSSHCOOL_API_INTEGRATIONS_HEROES_PASSWORD}
            RSSHCOOL_API_INTEGRATIONS_DISCORD_GRATITUDE_URL: ${RSSHCOOL_API_INTEGRATIONS_DISCORD_GRATITUDE_URL}
            RSSHCOOL_API_HIRERS: ${RSSHCOOL_API_HIRERS}
            RSSHCOOL_API_AWS_SECRET_ACCESS_KEY: ${RSSHCOOL_API_AWS_SECRET_ACCESS_KEY}
            RSSHCOOL_API_AWS_ACCESS_KEY_ID: ${RSSHCOOL_API_AWS_ACCESS_KEY_ID}
            RSSHCOOL_API_AWS_CERTIFICATE_GENERATION_URL: ${RSSHCOOL_API_AWS_CERTIFICATE_GENERATION_URL}
            RSSHCOOL_API_AWS_CERTIFICATE_GENERATION_API_KEY: ${RSSHCOOL_API_AWS_CERTIFICATE_GENERATION_API_KEY}
            RSSHCOOL_API_AWS_TASK_API_URL: ${RSSHCOOL_API_AWS_TASK_API_URL}
            RSSHCOOL_API_AWS_TASK_API_KEY: ${RSSHCOOL_API_AWS_TASK_API_KEY}
    proxy:
        image: rsschool/proxy:latest
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
        ports:
            - 80:8080
            - 443:443
        depends_on:
            - api
            - ui
